server:
  port: 9191

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/dbauth?createDatabaseIfNotExist=true
    username: admin
    password: admin123!
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace


security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
