server:
  port: 9191


spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/dbauth?createDatabaseIfNotExist=true
    username: admin
    password: admin123!
    initialization-mode: always
    continue-on-error: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
      springframework:
        security : DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true


security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
    resource:
      prefer-token-info: true
      service-id: auth-server
      token-info-uri: http://auth-server/oauth/check_token
      token-type: bearer



eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 3600

